MIN_ENEMY_HP = 3
MAX_ENEMY_HP = 9

PLAYER1_POS = [300, 200]
PLAYER2_POS = [500, 200]

PLAYER_MAX_HEALTH = 10
PLAYER_GRACE_PERIOD = 0.4
PLAYER_LASER_COOLDOWN = 0.1
PLAYER_SWORD_COOLDOWN = 1.6
PLAYER_AIR_RESISTANCE = 0.01
PLAYER_FRICTION = 0.15
PLAYER_MAX_SPEED = 300.0
PLAYER_JUMP_SPEED = 700.0
PLAYER_SPEED_INCREMENT = 50.0

ENEMY_GRACE_PERIOD = 0.4
ENEMY_MAX_SPEED = 200
ENEMY_JUMP_SPEED = 700

LASER_PARTICLE_MIN_SPEED = 30
LASER_PARTICLE_MAX_SPEED = 50
LASER_PARTICLE_MIN_LIFETIME = 0.3
LASER_PARTICLE_MAX_LIFETIME = 0.6
LASER_PARTICLE_COUNT = 7

SWORD_PARTICLE_MIN_SPEED = 30
SWORD_PARTICLE_MAX_SPEED = 50
SWORD_PARTICLE_MIN_LIFETIME = 0.3
SWORD_PARTICLE_MAX_LIFETIME = 0.6
SWORD_PARTICLE_COUNT = 7

PLAYER_HIT_PARTICLE_MIN_SPEED = 50
PLAYER_HIT_PARTICLE_MAX_SPEED = 80
PLAYER_HIT_PARTICLE_MIN_LIFETIME = 0.3
PLAYER_HIT_PARTICLE_MAX_LIFETIME = 0.6
PLAYER_HIT_PARTICLE_COUNT = 10

ENEMY_HIT_PARTICLE_MIN_SPEED = 30
ENEMY_HIT_PARTICLE_MAX_SPEED = 50
ENEMY_HIT_PARTICLE_MIN_LIFETIME = 0.3
ENEMY_HIT_PARTICLE_MAX_LIFETIME = 0.6
ENEMY_HIT_PARTICLE_COUNT = 7

ENEMY_DEATH_PARTICLE_MIN_SPEED = 50
ENEMY_DEATH_PARTICLE_MAX_SPEED = 80
ENEMY_DEATH_PARTICLE_MIN_LIFETIME = 0.9
ENEMY_DEATH_PARTICLE_MAX_LIFETIME = 1.5
ENEMY_DEATH_PARTICLE_COUNT = 10

PARTICLE_SPEED_SCALE = 10.0
PARTICLE_LIFETIME_SCALE = 10.0
PARTICLE_COUNT_SCALE = 7.0

SWORD_LIFETIME = 0.25

